Update README.md
fjromeero/MusicalFriends pull request #1
Opened 2022-09-22 12:28 UTC by fjromeero

* [ ✔️] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [✔️ ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
* [✔️ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
* [ ✔️] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-24 09:00 UTC, JJ requested changes
Por favor, pon claramente la lógica de negocio que piensas usar.

2022-09-24 09:00 UTC, JJ commented on README.md
> +  Con esta aplicación recibirás según el analísis de tu historial de lecturas totales y el de últimas lecturas, nuevas obras para leer, teniendo en cuenta los géneros mas repetidos en dichas obras y
"Además" casi nunca cabe en un producto mínimamente viable.

2022-09-24 09:00 UTC, JJ commented on README.md
> +  En un principio he considerado la programación de esta aplicación en Python.
En ningún sitio hemos dicho que digáis el idioma, pero sí que mencionéis explícitametne la lógica de negocio.

2022-09-26 14:10 UTC, fjromeero commented on README.md
> +  En un principio he considerado la programación de esta aplicación en Python.
> Por favor, pon claramente la lógica de negocio que piensas usar.

2022-09-26 14:10 UTC, fjromeero commented on README.md
> +  Con esta aplicación recibirás según el analísis de tu historial de lecturas totales y el de últimas lecturas, nuevas obras para leer, teniendo en cuenta los géneros mas repetidos en dichas obras y
Listo

2022-09-26 15:32 UTC, JJ requested changes
Como ya sabes, es el segundo sistema del mismo tipo. Aparte de lo comentado (que también lo hice en el otro caso) tendrás que diferenciarlo lo suficiente como para que quede claro que es trabajo autónomo.

2022-09-26 15:32 UTC, JJ commented on README.md
> +  Con esta aplicación recibirás según el analísis de tu historial de lecturas totales y el de últimas lecturas, nuevas obras para leer, teniendo en cuenta los géneros mas repetidos en dichas obras y
Espero que sepas como proporcionar al sistema de recomendación estas historias sin que el usuario tenga nada que descargar.

2022-09-26 15:32 UTC, JJ commented on README.md
> +  - Gente con experiencia, sistema de contenido :  a traves de la evaluación de obras previamente leidas por el usuario (las cuales han de ser introducidas previamente por el usuario haciendo uso de
"Que coincidan" es simplemente búsqueda, igual que el resto de la lógica de negocio. Por favor, da algunas pistas sobre qué lógica de negocio vas a usar, cómo la vas a validar y por qué es suficientemente compleja para esta asignatura.

2022-09-29 11:25 UTC, fjromeero commented on README.md
> +  - Gente con experiencia, sistema de contenido :  a traves de la evaluación de obras previamente leidas por el usuario (las cuales han de ser introducidas previamente por el usuario haciendo uso de
Creo que ya lo explique un poco mejor

2022-09-29 15:31 UTC, JJ requested changes
Lo siento, no creo que con este problema puedas hacer algo suficientemente diferente, cuando además no pareces tener muy clara cuál es la lógica de negocio (que es efectivamente cómo se resuelve el problema)

2022-09-29 15:31 UTC, JJ commented on README.md
> +  Con esta aplicación recibirás según el analísis de tu historial de lecturas totales y el de últimas lecturas (solo deberá introducir sus datos de su cuenta de MyAnimeList), nuevas obras para leer,
Typo: analísis
MyAnimeList también lo va a usar otro compañero. Por favor, dejadme que os insista en que no uséis los mismos recursos, ni la misma lógica de negocio. "Los géneros más repetidos" es simplemente búsqueda, y no dices como vs a tener en cuenta la puntuación (ni cómo te afecta a ti esa puntuación)

2022-09-29 19:07 UTC, fjromeero commented
@JJ  de acuerdo pero es que tampoco se me ocurre ningún otro problema sobre el que desarrollar el proyecto

2022-09-29 19:10 UTC, JJ commented
Mira los datos abiertos sugeridos en el guión, o cualquier otro que te interese, aunque no sea abierto. Si no lo es, extraer la información es parte de la lógica de negocios.

2022-09-30 11:38 UTC, fjromeero commented
@JJ propuse una nueva idea

2022-09-30 11:50 UTC, JJ approved these changes
Voy a aprobarlo porque lo tengo fresco y lo hemos hablado esta mañana, y sé que te lo has currado. Pero realmente deberías de dar una pista de cuál es la lógica de negocio que vas a usar, porque necesitarás procesar de alguna forma los géneros (y los moods o lo que sea), y sobre todo no trabajar inicialmente con el API de spotify hasta que no vayas a producción.Tenlo en cuenta para el siguiente objetivo.

Esto puedes especificarlo antes de mergear (pero no pidas más revisiones, ya está aprobado) o antes del siguiente, lo que prefieras.

2022-10-01 09:40 UTC, merged