Creada carpeta docs
fjromeero/MusicalFriends pull request #3
Opened 2022-10-10 08:14 UTC by fjromeero

2022-10-10 18:53 UTC, fjromeero commented
No estoy seguro si debería añadir alguna user story más

2022-10-13 10:54 UTC, fjromeero commented
@alvarogaro  Listo creo que ya lo resolví , aunque no estoy seguro del todo

2022-10-17 18:20 UTC, JJ commented
@alvarogaro Tendrías que revisarlo de nuevo a ver si ha hecho lo que le comentas y aprobarlo o pedir de nuevo cambios.

2022-10-21 08:28 UTC, fjromeero commented
@JJ listo para revisión

2022-10-21 09:45 UTC, JJ requested changes
Los milestones siguen sin reflejar claramente productos mínimamente viables.

2022-10-21 09:45 UTC, JJ commented on docs/planteamiento.md
> +- [[M2] Implementación de la interfaz de usuario](https://github.com/fjromeero/MusicalFriends/milestone/3)
En ningún momento hemos hablado de implementar la interfaz de usuario.

2022-10-21 09:45 UTC, JJ commented on docs/planteamiento.md
> +- [[M0] Fichero/s con el modelo de datos](https://github.com/fjromeero/MusicalFriends/milestone/1)
El modelo *de datos* es un concepto que se usa en implementación de bases de datos para hablar de cómo se va a almacenar la información. En ningún momento hemos hablado de modelo de datos, sino de modelo *del problema*

2022-10-21 18:39 UTC, fjromeero commented
@JJ listo para revisión

2022-10-22 11:45 UTC, JJ requested changes
Creo que, más allá de probar diferentes combinaciones de palabras, tienes que entender de qué se trata cada uno de los milestones o PMVs, qué hace falta para empezar a trabajar (tal como lo expliqué en clase varias veces) y qué hace falta para seguir.

2022-10-22 11:45 UTC, JJ commented on docs/planteamiento.md
> +- [[M0] Módulo que defina la estructura de datos que va almacenar los datos del usuario y los géneros, sin implementación](https://github.com/fjromeero/MusicalFriends/milestone/1)
¿Cómo sabes que ese módulo es viable? ¿Como no puede representar el modelo *de datos* tampoco representa ningún modelo? ¿Entiendes de verdad lo que implica el primer milestone de un proyecto?

2022-10-22 11:45 UTC, JJ commented on docs/planteamiento.md
> +- [[M1] Código de la clase/es usadas para implementar la lógica de negocio necesaria para recomendar otros usuarios en función de los géneros más escuchados](https://github.com/fjromeero/MusicalFrien
¿Por qué el anterior era "módulo" y este "código"? ¿Y el siguiente implementación? ¿Qué diferencia hay? ¿Qué relación hay este este y el anterior? En el anterior sólo has puesto "usuarios" y "géneros", sin ninguna relación aparente con ningún problema ni con este milestone.

2022-10-24 09:56 UTC, fjromeero commented
@JJ listo para revisión

2022-10-24 09:58 UTC, fjromeero commented
Estuve este fin de semana leyendo todas las diapositivas que usted subió , etc y creo que están correctas

2022-10-24 10:10 UTC, JJ approved these changes
Podías haber puesto más milestones, pero ya habrá tiempo de hacerlo.

2022-10-24 10:16 UTC, merged